# Generated by Django 5.1.2 on 2025-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_bio_usuario_birth_date_usuario_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
