# Generated by Django 5.1.2 on 2025-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
