# Generated by Django 5.1.2 on 2025-11-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reporte_aprobado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comentario',
            name='comentario_es_apro_1f9915_idx',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='es_aprobado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_aprobacion',
        ),
    ]
