# Generated by Django 5.1.2 on 2025-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_comentario_comentario_es_apro_1f9915_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
