# Generated by Django 5.1.2 on 2025-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reporte_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='url_imagen',
            field=models.TextField(default=''),
        ),
    ]
