# Generated by Django 5.1.2 on 2025-12-09 20:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reporte_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenreporte',
            name='ruta_archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='url_imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
