# Generated by Django 5.1.2 on 2025-12-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_imagenreporte_ruta_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
